event_data = {'version': '1.0', 'resource': '/auth/sample', 'path': '/dev/auth/sample', 'httpMethod': 'POST',
                  'headers': {
                      'Content-Length': '21',
                      'Content-Type': 'application/json',
                      'Cookie': 'CLU-TK1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjbGFzc3UuY28ua3IiLCJpYXQiOjE2NzU5Mzk4NTUuNjg4NTQ0LCJleHAiOjE3MDc0NzU4NTUuNjg4NTQ0LCJ1c2VyX2lkIjoiZ0FBQUFBQmo1TkFQQUx2UzRHUTVkdUE2R0x4MlNzbVFWM2FTbmhNZFM0Tm1wdHVkMVVELWpCX3hUckQ0UXU4NWg1SVNDcVZ3MFZxZUtXSEphd09PQUhuQW56bVFrS3VoLUE9PSIsInNlc3Npb25faWQiOm51bGx9.wZCtLlBEUgV3rbEuU3jZIyfrvt_QAsMdTQVV92As1Mk',
                      'Host': 'qqlmkz187k.execute-api.ap-northeast-2.amazonaws.com',
                      'Postman-Token': '06f1a0ef-78ae-43fc-8bae-bb79f9194cbd', 'User-Agent': 'PostmanRuntime/7.30.0',
                      'X-Amzn-Trace-Id': 'Root=1-63e4d0f8-67bb5c676a8da66d4d830a5e', 'X-Forwarded-For': '175.114.1.130',
                      'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https', 'accept': '*/*',
                      'accept-encoding': 'gzip, deflate, br', 'cache-control': 'no-cache'},
                  'requestContext': {
                      "apiRequestId": "fVTgogSToE0EP0w\u003d",
                      "routeKey": "POST Internal authorizer",
                      "requestId": "test"
                  },
                  'multiValueHeaders': {
                      'Content-Length': ['21'],
                      'Content-Type': ['application/json'],
                      'Cookie': [
                          'CLU-TK1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjbGFzc3UuY28ua3IiLCJpYXQiOjE2NzU5Mzk4NTUuNjg4NTQ0LCJleHAiOjE3MDc0NzU4NTUuNjg4NTQ0LCJ1c2VyX2lkIjoiZ0FBQUFBQmo1TkFQQUx2UzRHUTVkdUE2R0x4MlNzbVFWM2FTbmhNZFM0Tm1wdHVkMVVELWpCX3hUckQ0UXU4NWg1SVNDcVZ3MFZxZUtXSEphd09PQUhuQW56bVFrS3VoLUE9PSIsInNlc3Npb25faWQiOm51bGx9.wZCtLlBEUgV3rbEuU3jZIyfrvt_QAsMdTQVV92As1Mk'
                      ],
                      'Host': ['qqlmkz187k.execute-api.ap-northeast-2.amazonaws.com'],
                      'Postman-Token': ['06f1a0ef-78ae-43fc-8bae-bb79f9194cbd'],
                      'User-Agent': ['PostmanRuntime/7.30.0'],
                      'X-Amzn-Trace-Id': ['Root=1-63e4d0f8-67bb5c676a8da66d4d830a5e'],
                      'X-Forwarded-For': ['175.114.1.130'], 'X-Forwarded-Port': ['443'],
                      'X-Forwarded-Proto': ['https'], 'accept': ['*/*'],
                      'accept-encoding': ['gzip, deflate, br'], 'cache-control': ['no-cache']},
                  'queryStringParameters': {'community_id': 'test', 'user_name': 'test'},
                  'multiValueQueryStringParameters': {'community_id': ['test']},
                  'requestContext': {'accountId': '370434405590', 'apiId': 'qqlmkz187k',
                                     'authorizer': {'claims': None, 'community_id': 'test', 'exp': 0, 'iat': 0,
                                                    'iss': 'classu.co.kr', 'scopes': None, 'session_id': None,
                                                    'user_id': '1'},
                                     'domainName': 'qqlmkz187k.execute-api.ap-northeast-2.amazonaws.com',
                                     'domainPrefix': 'qqlmkz187k', 'extendedRequestId': 'AEWW5ggMoE0EQCg=',
                                     'httpMethod': 'POST',
                                     'identity': {'accessKey': None, 'accountId': None, 'caller': None,
                                                  'cognitoAmr': None,
                                                  'cognitoAuthenticationProvider': None,
                                                  'cognitoAuthenticationType': None,
                                                  'cognitoIdentityId': None, 'cognitoIdentityPoolId': None,
                                                  'principalOrgId': None, 'sourceIp': '175.114.1.130', 'user': None,
                                                  'userAgent': 'PostmanRuntime/7.30.0', 'userArn': None},
                                     'path': '/dev/auth/sample', 'protocol': 'HTTP/1.1',
                                     'requestId': 'AEWW5ggMoE0EQCg=',
                                     'requestTime': '09/Feb/2023:10:54:48 +0000', 'requestTimeEpoch': 1675940088691,
                                     'resourceId': 'POST /auth/sample', 'resourcePath': '/auth/sample', 'stage': 'dev'},
                  'pathParameters': None, 'stageVariables': {'postfix': 'dev'}, 'body': '{\n    "userId": "2"\n}',
                  'isBase64Encoded': False}